apiVersion: v1
kind: Template
metadata:
  name: ppt-lmi
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
  spec:
    replicas: ${{REPLICAS}}
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:${APPLICATION_TAG}
          namespace: ${PROJECT_NAMESPACE}
      type: ImageChange
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
          deploymentconfig: ${APPLICATION_NAME}
      spec:
        restartPolicy: Always
        dnsPolicy: ClusterFirst
        serviceAccount: ${SERVICE_ACCOUNT}
        serviceAccountName: ${SERVICE_ACCOUNT}
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        resources:
          limits:
            memory: ${MEMORY_LIMIT}
            cpu: ${CPU_LIMIT}
        containers:
          - name: ${APPLICATION_NAME}
            image: ${OC_DOCKER_REGISTRY}/${PROJECT_NAMESPACE}/${APPLICATION_NAME}:${APPLICATION_TAG}
            imagePullPolicy: Always
            envFrom:
              - configMapRef:
                  name: inte-ppt-lmi
            ports:
            - containerPort: 8009
              name: jboss
              protocol: TCP
            - containerPort: 8080
              name: ppt-lmi
              protocol: TCP
            volumeMounts: []
            command:
              - run1.sh
            args:
              - "-b"
              - "0.0.0.0"
              - "-c"
              - "web"
        volumes: []
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    clusterIP: None
    ports:
    - name: jboss
      port: 8009
      protocol: TCP
      targetPort: 8009
    - name: ppt-lmi
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${APPLICATION_NAME}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: ${APPLICATION_NAME}
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: ImageStream
  metadata:
    generation: 1
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: ${SIA_DOCKER_REGISTRY}/${SIA_PROJECT_NAMESPACE}/${APPLICATION_NAME}:${APPLICATION_TAG}
      importPolicy: 
        insecure: true
      name: ${APPLICATION_TAG}
      referencePolicy:
        type: ""
parameters:
- description: The namespace of the project where deploy the application (avv-sit, avv-uat)
  displayName: Project Namespace
  name: PROJECT_NAMESPACE
  required: true
  value: avv-sit
- description: The tag image to trigger app
  displayName: Application TAG
  name: APPLICATION_TAG
  required: true
  value: dev-ready
- description: OC internal docker registry
  displayName: OC internal docker registry
  name: OC_DOCKER_REGISTRY
  required: true
  value: 172.30.1.1:5000
- description: Namespace where the docker images are deployed 
  displayName: Namespace SIA registry
  name: SIA_PROJECT_NAMESPACE
  required: true
  value: web
- description: SIA docker registry
  displayName: SIA docker registry
  name: SIA_DOCKER_REGISTRY
  required: true
  value: npasregt01:5000
- description: Service account
  displayName: Service account
  name: SERVICE_ACCOUNT
  required: true
  value: lmi
- description: The name of the application
  displayName: Application name
  name: APPLICATION_NAME
  required: true
- description: The version of the application to deploy
  displayName: Application version
  name: APPLICATION_VERSION
  required: true
  value: dev-read
- description: Replicas
  displayName: Replicas
  name: REPLICAS
  required: true  
  value: "1"
- description: The memory limit of the application expressed in megabyte (Mi) or gigabyte (Gi)
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 512Mi
- description: The cpu limit expressed in millicore (m)
  displayName: CPU Limit
  name: CPU_LIMIT
  required: true
  value: 300m
